### ISSUE TITLE
Flycheck can't find python libraries

### ISSUE THREAD

**Issue by kenogo** [shlevy/nix-buffer#16]
I'm not sure if I'm using this correctly. But my project is set up like this:

```
project-dir
|__dir-locals.nix
|__python
   |__program.py
```

My `dir-locals.nix` contains the following:

```
let pkgs = import <nixpkgs> {}; in
  pkgs.nixBufferBuilders.withPackages [
    pkgs.python3
    pkgs.python36Packages.uproot
    pkgs.python36Packages.tensorflow
    pkgs.python36Packages.matplotlib
    pkgs.python36Packages.numpy
    pkgs.python36Packages.pandas
    pkgs.python36Packages.scipy
    pkgs.python36Packages.Keras
  ]
```

So with this setup, I first open `program.py` in emacs and then run `nix-buffer`. The first time I did it, it even asked me whether to trust the generated elisp code. I hit `y` but nothing happened after that. Flycheck still complains about not being able to find the python libraries. Now, when I run `nix-buffer`, it doesn't even ask me if I trust the elisp code anymore (I guess because it remembered that).

Did I do anything wrong or is this a bug?

**Comment by shlevy** [comment]
It's been a bit since I've looked at this, but if I recall correctly currently `withPackages` just puts things into `PATH` unless one of the packages has an `emacsBufferSetup`. So if python doesn't have that, then the generated elisp won't know to add those libraries to a python path.

**Comment by shlevy** [comment]
Feel free to reopen if this is still something you'd like fixed, trying to clean up issue tracking.
