### ISSUE TITLE
Is anyone still using this package?

### ISSUE THREAD

**Issue by DamienCassou** [shlevy/nix-buffer#17]
There doesn't seem to be much changes on this package anymore. Is anyone still using it or did everyone migrated to something different (what?)?

**Comment by shlevy** [comment]
I haven't been for a while. I'm just going without for now.

**Comment by DamienCassou** [comment]
Are you still using Emacs? How do you make Emacs tools (e.g., lsp, flycheck, haskell, ...) work in shell.nix-based projects?

**Comment by shlevy** [comment]
I just use general syntax checking and use shell tools to actual typecheck for now. I think nix-buffer is basically the right approach, just hasn't been a major priority.

**Comment by costrouc** [comment]
I use this package daily since this is the only way that I am aware of having a "virtual environment" per file. My workflow I create a file named `numpy.org`.

```org
#+title: numpy

 - tags :: [[id:553403f2-2f30-4ac6-85e7-1c3b12f2f00a][python]]

#+begin_src nix :tangle yes
  { pkgs ? import <nixpkgs> { } }:

  pkgs.nixBufferBuilders.withPackages [
    pkgs.docker-compose
    (pkgs.python38.withPackages(ps: with ps; [ numpy ]))
  ]
#+end_src

* References

# Local Variables:
# nix-buffer-root-file: "numpy.nix"
# End:
```

I then write the nix buffer file via `C-c C-v C-t` (org-tangle) finally run `nix-buffer`. This allows a nix environment for all org babel code cells. Really does all that I need! Thanks @shlevy for the awesome package.

**Comment by AleXoundOS** [comment]
> How do you make Emacs tools (e.g., lsp, flycheck, haskell, ...) work in shell.nix-based projects?

For `Makefile` C/C++ projects `compile_commands.json` can be generated with [compiledb](https://github.com/nickdiego/compiledb) which is read by emacs lsp-mode. For haskell I used [haskell.nix](https://input-output-hk.github.io/haskell.nix/tutorials/development.html#emacs-ide-support) infrastructure with [nix-direnv](https://github.com/nix-community/nix-direnv) integration.

**Comment by shlevy** [comment]
FYI I'm likely to start using this again, with a clean integration with flakes.

**Comment by shlevy** [comment]
Resuming work on nix-buffer.
