### ISSUE TITLE
Does nixBufferBuilders work on Emacs 28+?

### ISSUE THREAD

**Issue by ashgillman** [shlevy/nix-buffer#31]
Thanks for this project. I appreciate it is an older piece of work, but seems to be the still only solution to load up an arbitrary nix file for a buffer? (direnv and envrc seem to be less suited)

I'm on Emacs 29. When I attempt to load in an env using nix-buffer, I get some errors that seem to break emacs to the point I'm struggling to pull up a stack trace.

```
Wrong number of arguments: (lambda (orig name) (if (and nixpkgs--is-nixpkgs-buffer (eq (aref name 0) 32)) (let ((buf (funcall orig name))) (progn (inherit-local-inherit-child buf) (save-current-buffer (set-buffer buf) (setq nixpkgs--buffer-count (1+ nixpkgs--buffer-count)) (add-hook 'kill-buffer-hook 'nixpkgs--decrement-buffer-count nil t))) buf) (funcall orig name))), 3
```

I assume that refers to here:

https://github.com/NixOS/nixpkgs/blob/c4fa270c64ab900fb55aa3a710861727d7337784/pkgs/build-support/emacs/buffer.nix#L18

`nixpkgs--around-generate` is advice added to `generate-new-buffer`.
I know little about advice-add, but I assume maybe it tries to call the advice function with the args to the original?
It seems `generate-new-buffer` had a new optional argument added in Emacs 28:
https://github.com/emacs-mirror/emacs/blob/7b30e11b2ac5cd360db7ee8b6aed07bd918b93a2/etc/NEWS.28#L3360

That was two years ago, but it seems nixpkgs' `buffer.nix` hasn't really been maintained since 2018.

Emacs versions:
```
GNU Emacs     v29.0.92         emacs-29.0.92
Doom core     v3.0.0-pre       HEAD -> master 24601b30 2023-08-07 20:34:53 +0200
Doom modules  v23.03.0-pre     HEAD -> master 24601b30 2023-08-07 20:34:53 +0200
```

**Comment by shlevy** [comment]
Can you try changing https://github.com/NixOS/nixpkgs/blob/c4fa270c64ab900fb55aa3a710861727d7337784/pkgs/build-support/emacs/buffer.nix#L27 to `(funcall orig nil)` and open a PR if that works?

**Comment by shlevy** [comment]
Can you try https://github.com/shlevy/nixpkgs/tree/nix-buffer-new-emacs ? I'll open a PR if it works

**Comment by ashgillman** [comment]
Works like a charm! Thank you very much, I'd drudged that far but didn't know enough elisp to complete the circle.

**Comment by ashgillman** [comment]
I think there is one more small compatibility issue: but I'm not using the functionality so maybe its not work worrying about fixing if there are no users?

I did get a warning: `Symbol’s value as variable is void: eshell-path-env`

It looks like this is now just `exec-path`
https://github.com/emacs-mirror/emacs/blob/7b30e11b2ac5cd360db7ee8b6aed07bd918b93a2/etc/NEWS.29#L422

So I guess the eshell-path-env line could be removed. However, I still don't get the correct environment when I launch an eshell. But as I mentioned, I'm not actually needing this functionality.

Within an org note, babel get the correct environment, which is what I'm looking for.

**Comment by shlevy** [comment]
Any chance you could try one more time? There is still `eshell-path-env` it's just not bound if the user hasn't ever loaded eshell, latest commit should fix this.

**Comment by ashgillman** [comment]
Of course, thanks for your help.
Yes, that works great!
