### ISSUE TITLE
Read directly from "default.nix"

### ISSUE THREAD

**Issue by matthewbauer** [shlevy/nix-buffer#4]
Lots of Nix projects already have a "default.nix" file with one derivation. Can the inputs of that be used to automatically setup nix-buffer without the dir-locals.nix?

/cc @shlevy

**Comment by shlevy** [comment]
Hmm... Since nix-buffer leads to arbitrary code execution, I'm a bit hesitant to have it pull anything that wasn't explicitly asked for. However, you can always have a `dir-locals.nix` in your `$HOME` that checks for a `root + "/default.nix"` and sets things up accordingly

**Comment by matthewbauer** [comment]
> Since nix-buffer leads to arbitrary code execution

Hmm... Let me think about this for a little bit but can't you rely on the directory locals confirmation here? My hope is to eventually have a "zero config" Nix IDE that lets me visit packages without going into a nix-shell subprocess.

**Comment by shlevy** [comment]
Hm... I mean yes, you're right. I'm not hugely in favor of this but not hugely opposed, I still think a top-level ~/dir-locals.nix can do this for people who want it but if you open a PR I'll probably merge it. Note that you can only use default.nix *after* you've walked all the way up to `/` to verify there's no dir-locals.nix

**Comment by shlevy** [comment]
Example of what I mean for `~/dir-locals.nix`
```nix
{ root }: let defnix = root + "/default.nix"; in if builtins.pathExists defnix then somethingWithDefnix else {}
```

**Comment by matthewbauer** [comment]
Okay, thanks! Here's what I've got so far (based on nixBuffer stuff):

```
{ root }:
let
  defnix = root + "/default.nix";
  pkgs = import <nixpkgs> {};
  inherit (pkgs) lib writeText runCommand;
  inherit (pkgs.emacsPackagesNg) inherit-local;
  withPackages = pkgs: let
      extras = map (x: x.emacsBufferSetup pkgs)
                   (builtins.filter (builtins.hasAttr "emacsBufferSetup") pkgs);
    in writeText "dir-locals.el" ''
      (require 'inherit-local "${inherit-local}/share/emacs/site-lisp/elpa/inherit-local-${inherit-local.version}/inherit-local.elc")
      ; Only set up nixpkgs buffer handling when we have some buffers active
      (defvar nixpkgs--buffer-count 0)
      (when (eq nixpkgs--buffer-count 0)
        (make-variable-buffer-local 'nixpkgs--is-nixpkgs-buffer)
        (defun nixpkgs--around-generate (orig name)
          (if (and nixpkgs--is-nixpkgs-buffer (eq (aref name 0) ?\s))
              (let ((buf (funcall orig name)))
                (progn
                  (inherit-local-inherit-child buf)
                  (with-current-buffer buf
                    (setq nixpkgs--buffer-count (1+ nixpkgs--buffer-count))
                    (add-hook 'kill-buffer-hook
                              'nixpkgs--decrement-buffer-count nil t)))
                buf)
            (funcall orig name)))
        (advice-add 'generate-new-buffer :around #'nixpkgs--around-generate)
        ; When we have no more nixpkgs buffers, tear down the buffer handling
        (defun nixpkgs--decrement-buffer-count ()
          (setq nixpkgs--buffer-count (1- nixpkgs--buffer-count))
          (when (eq nixpkgs--buffer-count 0)
            (advice-remove 'generate-new-buffer #'nixpkgs--around-generate)
            (fmakunbound 'nixpkgs--around-generate)
            (fmakunbound 'nixpkgs--decrement-buffer-count))))
      (setq nixpkgs--buffer-count (1+ nixpkgs--buffer-count))
      (add-hook 'kill-buffer-hook 'nixpkgs--decrement-buffer-count nil t)
      ; Add packages to PATH and exec-path
      (make-local-variable 'process-environment)
      (put 'process-environment 'permanent-local t)
      (inherit-local 'process-environment)
      ; setenv modifies in place, so copy the environment first
      (setq process-environment (copy-tree process-environment))
      (setenv "PATH" (concat "${lib.makeSearchPath "bin" pkgs}:"
                     (getenv "PATH")))
      (inherit-local-permanent exec-path (append
                               '(${builtins.concatStringsSep " "
                                 (map (p: "\"${p}/bin\"") pkgs)}) exec-path))
      (setq nixpkgs--is-nixpkgs-buffer t)
      (inherit-local 'nixpkgs--is-nixpkgs-buffer)
      ${lib.concatStringsSep "\n" extras}
    '';
    drv = import defnix;
in if builtins.pathExists defnix then
  withPackages (drv.buildInputs ++ drv.nativeBuildInputs)
else {}
```

and this in my init.el:

```
(require 'nix-buffer)
(require 'projectile)

(defun nix-buffer-projectile ()
  "A convenient function to add to projectile-mode-hook.

Enables nix-buffer whenever it finds you are in a Nix
project (containing a default.nix file)"
  (when (and (not (file-remote-p default-directory))
             (projectile-project-p)
             (eq (projectile-project-type) 'nix))
    (nix-buffer)))

(projectile-register-project-type 'nix '("default.nix") "nix-build")
(add-hook 'projectile-mode-hook 'nix-buffer-projectile)
```

I'll keep this updated in the future and if things work out open a PR.

**Comment by shlevy** [comment]
Hmm any reason you can't use `nixBufferBuilders.withPackages` directly?

**Comment by matthewbauer** [comment]
> Hmm any reason you can't use nixBufferBuilders.withPackages directly?

Mostly it's just easier to make changes to. I want to get it to set things like "CFLAGS" and "CXXFLAGS" so I can have flycheck work properly.

**Comment by shlevy** [comment]
@matthewbauer I'd rather get those fixed upstream, if possible.

**Comment by matthewbauer** [comment]
@shlevy So I think this should be possible with Nix but I can't figure out how to do it:

Given a derivation, list all of the environment variables that would be set in that derivations "nix-shell" (maybe run the configurationPhase too).

So I want the output of:
```
nix-shell . --run "echo \$PATH"
```

How do I do that within a Nix expression?

**Comment by matthewbauer** [comment]
Ok here's what I've got:

```
{ root }:
let
  defnix = root + "/default.nix";
  pkgs = import <nixpkgs> {};
  inherit (pkgs) lib writeText runCommand;
  inherit (pkgs.emacsPackagesNg) inherit-local;
  inherit (pkgs.nixBufferBuilders) withPackages;
  drv = import (builtins.toPath defnix);
  packageEnv = pkg: lib.overrideDerivation pkg (old: {
    phases = [ "installPhase" ];
    installPhase = ''${pkgs.jq}/bin/jq -n env > $out'';
  });
  withPackage = pkg: writeText "dir-locals.el" ''
    (require 'json)
    (defun setenvs (env)
      "Set environment variables from ENV alist."
      (dolist (x env)
        (setenv (symbol-name (car x)) (cdr x))))
    (setenvs (json-read-file "${packageEnv pkg}"))
  '';
in if builtins.pathExists defnix then
  withPackage drv
else {}
```

need to clean it up so that it respects buffer local stuff though.

**Comment by matthewbauer** [comment]
@shlevy Hope I'm not annoying you too much! But I've got one more question:

What's the reasoning behind the ```nixpkgs--buffer-count``` logic? Are there issues with inherit-local that I'm not seeing yet?

**Comment by shlevy** [comment]
Ah, yeah, in nixpkgs I think I just iterate over buildInputs but exporting the whole `env` is another way to go.

**Comment by shlevy** [comment]
The buffer-count logic is just so we can tear down advice around core functions when they're not needed. Probably premature optimization, honestly. I wish there was buffer-local advice though...

**Comment by shlevy** [comment]
This will be solved in the [flakes project](https://github.com/users/shlevy/projects/1), as we will be pulling repo-specific information from a well-known output from `flake.nix`
